{
	"version": 1498510513,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/images-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/menu-sheet0.png",
		"images/chao-sheet0.png",
		"images/bloco-sheet0.png",
		"images/spaw-sheet0.png",
		"images/akili-sheet0.png",
		"images/enemy-sheet0.png",
		"images/porta-sheet0.png",
		"images/colisor-sheet0.png",
		"images/enemy2-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/fogo-sheet0.png",
		"images/tiledbackground2.png",
		"images/tiledbackground3.png",
		"images/tiledbackground4.png",
		"images/sprite4-sheet0.png",
		"images/tiledbackground6.png",
		"images/tiledbackground7.png",
		"images/tiledbackground8.png",
		"images/tiledbackground13.png",
		"images/tiledbackground14.png",
		"images/arvore1-sheet0.png",
		"images/arvo3-sheet0.png",
		"images/arvore-sheet0.png",
		"images/arvore2-sheet0.png",
		"images/foguinho-sheet0.png",
		"images/sprite8-sheet0.png",
		"images/tiledbackground15.png",
		"images/fim-sheet0.png",
		"images/lava-sheet0.png",
		"images/vidavazio-sheet0.png",
		"images/vida-sheet0.png",
		"images/escudos_verde-sheet0.png",
		"images/escudosvazio-sheet0.png",
		"images/1m-sheet0.png",
		"images/1m-sheet1.png",
		"images/1m-sheet2.png",
		"images/fundoempre-sheet0.png",
		"images/portal-sheet0.png",
		"images/mascara-sheet0.png",
		"images/mascara2-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/faset-sheet0.png",
		"images/ogum-sheet0.png",
		"images/aganju-sheet0.png",
		"images/cenario-sheet0.png",
		"images/chaoo-sheet0.png",
		"images/tiledbackground.png",
		"images/tiledbackground10.png",
		"images/coqueiros-sheet0.png",
		"images/enemy_idle_-sheet0.png",
		"images/enemy_idle_-sheet1.png",
		"images/enemy_idle_-sheet2.png",
		"images/bullskullvector-sheet0.png",
		"images/boladefogo-sheet0.png",
		"images/boladefogo-sheet1.png",
		"images/sprite10-sheet0.png",
		"images/mascara_pont-sheet0.png",
		"images/masks157749_960_-sheet0.png",
		"images/spikes-sheet0.png",
		"images/blacksmoke-sheet0.png",
		"images/blacksmoke2-sheet0.png",
		"media/videoplayback (1).m4a",
		"media/videoplayback (1).ogg",
		"media/videoplayback (2).m4a",
		"media/videoplayback (2).ogg",
		"media/videoplayback.m4a",
		"media/videoplayback.ogg",
		"media/god of war ii ost- death of kratos (online-audio-converter.com).m4a",
		"media/god of war ii ost- death of kratos (online-audio-converter.com).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}