{
	"version": 1512155956,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/tilemap.png",
		"images/limites-sheet0.png",
		"images/iinimigo-sheet0.png",
		"images/iinimigo-sheet1.png",
		"images/iinimigo-sheet2.png",
		"images/fim-sheet0.png",
		"images/itorre-sheet0.png",
		"images/itorre-sheet1.png",
		"images/itorre-sheet2.png",
		"images/itorre-sheet3.png",
		"images/ibase-sheet0.png",
		"images/iefdabala-sheet0.png",
		"images/ibala-sheet0.png",
		"images/iname-sheet0.png",
		"images/imenu-sheet0.png",
		"images/ibotãoplay-sheet0.png",
		"images/ibotãogame-sheet0.png",
		"images/ibotãocreditos-sheet0.png",
		"images/ilivre-sheet0.png",
		"images/ilivre-sheet1.png",
		"images/itrancado-sheet0.png",
		"images/itabela-sheet0.png",
		"images/itorrecomprar-sheet0.png",
		"images/itorrecomprar-sheet1.png",
		"images/itorrecomprar-sheet2.png",
		"images/ivender-sheet0.png",
		"images/icompra-sheet0.png",
		"images/voltar-sheet0.png",
		"images/frente-sheet0.png",
		"images/tabela-sheet0.png",
		"images/credits.png",
		"images/sprite-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/i6-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/sprite8-sheet0.png",
		"media/pumped up kicks [8 bit universe tribute to foster the people] (online-audio-converter.com).ogg",
		"media/guitarra humana kkkkkkkkkkk (online-audio-converter.com) (1).m4a",
		"media/guitarra humana kkkkkkkkkkk (online-audio-converter.com) (1).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"pathfind.js"
	]
}